<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Shah, Alex Li">
<meta name="dcterms.date" content="2024-04-25">

<title>Predicting NBA Rookie Success from College Performance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="code_files/libs/clipboard/clipboard.min.js"></script>
<script src="code_files/libs/quarto-html/quarto.js"></script>
<script src="code_files/libs/quarto-html/popper.min.js"></script>
<script src="code_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="code_files/libs/quarto-html/anchor.min.js"></script>
<link href="code_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="code_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="code_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="code_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="code_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting NBA Rookie Success from College Performance</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Shah, Alex Li </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 25, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Predictive modeling of NBA rookie success based on college performance statistics provides crucial insights for sports analytics. This analysis utilizes historical data to establish relationships between collegiate achievements and professional performance in the NBA, thereby supporting decision-making in sports management.</p>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<p>How can NBA rookie success, measured by points per game, be predicted from their college basketball statistics? This study employs statistical modeling techniques to forecast NBA outcomes from detailed collegiate performance metrics.</p>
</section>
<section id="data-description" class="level3">
<h3 class="anchored" data-anchor-id="data-description">Data Description</h3>
<p>This study employs two primary datasets:</p>
<ol type="1">
<li><strong>College Basketball Dataset</strong>: Consists of detailed player statistics from NCAA college basketball spanning 2009 to 2021. This dataset includes metrics such as player efficiency ratings and scoring averages.</li>
</ol>
<p>[Source: https://www.kaggle.com/datasets/adityak2003/college-basketball-players-20092021/data]</p>
<ol start="2" type="1">
<li><strong>NBA Player Statistics</strong>: Contains performance data for NBA rookies’ first season from 2009 to 2021, focusing on points per game and efficiency metrics.</li>
</ol>
<p>[Source: https://www.kaggle.com/datasets/raunakpandey030/nba-player-stats]</p>
</section>
<section id="key-variables" class="level3">
<h3 class="anchored" data-anchor-id="key-variables">Key Variables:</h3>
<ul>
<li><code>College_points</code>: Average points scored per game in the player’s final college season.</li>
<li><code>eFG%</code>: Effective field goal percentage in college.</li>
<li><code>TS%</code>: True shooting percentage in college.</li>
<li><code>NBA_points</code>: Average points per game during the player’s rookie NBA season.</li>
</ul>
</section>
<section id="data-cleaning-and-merging-process" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-merging-process">Data Cleaning and Merging Process</h3>
<p>The data was meticulously cleaned to ensure consistency and relevance to the study’s goals. This involved: - Renaming columns for clarity. - Filtering records to retain only the last year of college and the first year in the NBA to focus on the transition period. - Removing duplicate entries and normalizing data formats for accurate merging.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...65`
• `` -&gt; `...66`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 61061 Columns: 66
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): player_name, team, conf, yr, ht, type, ...65
dbl (59): GP, Min_per, Ortg, usg, eFG, TS_per, ORB_per, DRB_per, AST_per, TO...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 14573 Columns: 31
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): Player, Pos, Tm, Year
dbl (27): Rk, Age, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="code_files/figure-html/eda-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="code_files/figure-html/eda-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="code_files/figure-html/eda-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The exploratory data analysis aims to correlate college performance metrics with NBA rookie success, focusing on points per game through visualizations that underscore data distribution and trends.</p>
<p>Relationship between College Points and NBA Rookie Points: This analysis begins with a scatter plot displaying the relationship between college scoring averages and NBA rookie points. Each data point represents a player, colored by their college conference, overlayed with a linear regression line. The plot suggests a positive correlation between college and NBA scoring, though variability is high. This variability may reflect differences in playing style, player roles, or other factors affecting a player’s transition from college to the NBA.</p>
<p>Effect of College Effective Field Goal Percentage on NBA Points: A second plot examines how college effective field goal percentage (eFG%) relates to NBA points. A linear fit indicates a modest positive correlation, implying that higher eFG% in college might predict better NBA performance. However, the relationship is not definitive, suggesting that eFG% may not fully predict NBA success without considering other contextual factors like the player’s role and gameplay system.</p>
<p>Impact of College True Shooting Percentage on NBA Points: The final plot explores the relationship between college true shooting percentage (TS%) and NBA rookie points. The positive trend shown by the green regression line suggests that TS%, which accounts for overall shooting efficiency including 3-pointers and free throws, might be a slightly better predictor of NBA success than eFG% alone.</p>
</section>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<section id="model-selection-process" class="level3">
<h3 class="anchored" data-anchor-id="model-selection-process">Model Selection Process</h3>
<p>In this study, we aimed to predict NBA rookie success, quantified by points per game, using their college basketball statistics. Given the continuous nature of our response variable, we considered regression models, which are well-suited for predicting quantitative outcomes. We selected two types of models for our analysis:</p>
<p><strong>Linear Regression</strong>: Chosen for its simplicity, interpretability, and widespread use in predictive analytics. Linear regression is particularly useful in understanding the direct relationship between each predictor variable and the response variable, providing clear insights into how each college performance metric might influence NBA success.</p>
<p><strong>Multilayer Perceptron (MLP) Regressor</strong>: Selected for its ability to model nonlinear relationships and interactions between predictors that linear regression might not capture. This model type is part of the neural networks family, offering the flexibility to learn complex patterns in the data, potentially leading to more accurate predictions.</p>
</section>
<section id="predictor-variables" class="level3">
<h3 class="anchored" data-anchor-id="predictor-variables">Predictor Variables</h3>
<p>The predictor variables initially included were: - <code>eFG%</code> (Effective Field Goal Percentage) - <code>TS%</code> (True Shooting Percentage) - <code>College_points</code> (Average points per game during the player’s final college season)</p>
<p>These variables were chosen due to their direct relationship with scoring performance, which is our primary measure of NBA success.</p>
</section>
<section id="data-splitting" class="level3">
<h3 class="anchored" data-anchor-id="data-splitting">Data Splitting</h3>
<p>The data was split into training and test sets with a 70-30 ratio, using a random seed for reproducibility (<code>random_state=999</code>). This split was chosen to provide a substantial training set for model development while leaving a sizable portion of data for testing model validity.</p>
</section>
<section id="model-enhancement-with-one-hot-encoding" class="level3">
<h3 class="anchored" data-anchor-id="model-enhancement-with-one-hot-encoding">Model Enhancement with One-Hot Encoding</h3>
<p>To improve the model’s performance, we introduced a categorical variable: - <code>conf</code> (Conference): This variable represents the college conference of each player, which could have an influence on the player’s transition to the NBA due to varying levels of competition across conferences.</p>
<p>One-hot encoding was applied to this categorical variable to convert it into a numerical format that could be used in our regression models. This allowed us to examine the impact of different conferences on NBA success.</p>
</section>
<section id="model-fitting-and-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="model-fitting-and-diagnostics">Model Fitting and Diagnostics</h3>
<p>Each model was trained using the respective fitting functions in R:</p>
<p>The Linear Regression model was fitted using the lm() function. The MLP model was fitted using the nnet() package, with specifications for the hidden layer structure and regularization to prevent overfitting.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = NBA_points ~ eFG + TS_per + College_points, data = train_data)

Residuals:
   Min     1Q Median     3Q    Max 
-5.730 -2.802 -1.263  1.619 17.216 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     4.44804    1.03273   4.307 1.89e-05 ***
eFG             0.06209    0.06164   1.007   0.3141    
TS_per         -0.07332    0.06717  -1.092   0.2754    
College_points  0.10153    0.03432   2.958   0.0032 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.096 on 706 degrees of freedom
Multiple R-squared:  0.01379,   Adjusted R-squared:  0.009598 
F-statistic:  3.29 on 3 and 706 DF,  p-value: 0.02025</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>a 3-5-1 network with 26 weights
options were - linear output units  decay=0.1
 b-&gt;h1 i1-&gt;h1 i2-&gt;h1 i3-&gt;h1 
  1.09   0.12   0.22  -0.50 
 b-&gt;h2 i1-&gt;h2 i2-&gt;h2 i3-&gt;h2 
 -3.82   1.28  -1.43   9.36 
 b-&gt;h3 i1-&gt;h3 i2-&gt;h3 i3-&gt;h3 
-12.76  -0.16   0.29   0.14 
 b-&gt;h4 i1-&gt;h4 i2-&gt;h4 i3-&gt;h4 
  9.39   0.27  -0.30  -2.57 
 b-&gt;h5 i1-&gt;h5 i2-&gt;h5 i3-&gt;h5 
  2.65  -7.57   8.36  -2.67 
  b-&gt;o  h1-&gt;o  h2-&gt;o  h3-&gt;o  h4-&gt;o  h5-&gt;o 
  5.60   2.45   4.88  11.29   5.01  -9.20 </code></pre>
</div>
</div>
</section>
<section id="model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="model-diagnostics">Model Diagnostics</h3>
<p>Residual Analysis: Residual plots were examined for patterns that might suggest inadequacies in the model forms. For the linear model, residuals were checked for homoscedasticity and normality.</p>
<p>Shapiro-Wilk Test: Conducted to test the normality of residuals in the linear regression model, where a significant result (p &lt; 2.2e-16) suggested deviations from normality, indicating potential issues with underlying assumptions.</p>
<p>Performance Metrics: Mean Squared Error (MSE) and R-squared were calculated for both models to assess their accuracy and explanatory power.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="code_files/figure-html/evalmetrics-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(linear_model)
W = 0.86995, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              Model      MSE         R2
1 Linear Regression 13.55590 0.01200178
2     MLP Regressor 14.38812 0.02530211</code></pre>
</div>
</div>
</section>
<section id="consideration-of-model-violations" class="level3">
<h3 class="anchored" data-anchor-id="consideration-of-model-violations">Consideration of Model Violations</h3>
<p>The low R-squared value from the linear model suggested limited explanatory power, prompting further exploration with the MLP model. Despite improved flexibility in capturing non-linear relationships with the MLP, the complexity did not substantially increase the explanatory power as reflected in the metrics. This suggests that further model tuning or alternative modeling approaches might be necessary to enhance predictive performance.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>We deployed two models: Linear Regression and Multilayer Perceptron (MLP) Regressor. The analysis presented here focuses on the output of these models, particularly examining how well they address the research questions through their predictive capabilities.</p>
<section id="model-performance-metrics" class="level3">
<h3 class="anchored" data-anchor-id="model-performance-metrics">Model Performance Metrics</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ModelMetrics'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:caret':

    confusionMatrix, precision, recall, sensitivity, specificity</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:Metrics':

    auc, ce, logLoss, mae, mse, msle, precision, recall, rmse, rmsle</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:base':

    kappa</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = NBA_points ~ eFG + TS_per + College_points, data = train_data)

Residuals:
   Min     1Q Median     3Q    Max 
-5.730 -2.802 -1.263  1.619 17.216 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     4.44804    1.03273   4.307 1.89e-05 ***
eFG             0.06209    0.06164   1.007   0.3141    
TS_per         -0.07332    0.06717  -1.092   0.2754    
College_points  0.10153    0.03432   2.958   0.0032 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.096 on 706 degrees of freedom
Multiple R-squared:  0.01379,   Adjusted R-squared:  0.009598 
F-statistic:  3.29 on 3 and 706 DF,  p-value: 0.02025</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Linear Model Test MSE: 13.5559033928784"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Linear Model Test R2: 0.0120017829344749"</code></pre>
</div>
</div>
<p>The evaluation of our models’ performance is based on two primary statistics: Mean Squared Error (MSE) and R-squared (R²), which provide insight into the models’ accuracy and the proportion of variance in NBA points they explain. <strong><em>Linear Regression Model:</em></strong> MSE: 13.55590 R²: 0.01200178 <strong><em>MLP Regressor:</em></strong> MSE: 14.38812 R²: 0.02530211</p>
<p>These metrics indicate a relatively low explanatory power for both models, highlighting the challenges in using collegiate performance alone to predict NBA success.</p>
</section>
<section id="visual-assessment-of-model-predictions" class="level3">
<h3 class="anchored" data-anchor-id="visual-assessment-of-model-predictions">Visual Assessment of Model Predictions</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="code_files/figure-html/plotting%20models-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To visually assess model performance, we plotted the actual versus predicted NBA points for both models:</p>
<p>The Linear Regression model shows a clustering of predictions around the lower range of NBA points, indicating limited predictive variability and a tendency to underpredict the performance of higher-scoring rookies. The MLP Regressor exhibits greater spread in predictions, suggesting it captures more complexity in the data. However, the spread includes significant prediction errors, as evident from points far from the line of perfect prediction. This visual comparison underscores the models’ struggles to accurately predict NBA rookie points and suggests potential areas for model refinement.</p>
</section>
<section id="interpretation-of-key-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-key-results">Interpretation of Key Results</h3>
<p>The coefficients from the Linear Regression model provide a quantitative measure of how each predictor influences NBA rookie success:</p>
<p>College Points: The positive coefficient (0.10153, p-value = 0.0032) implies that higher scores in college predict higher NBA rookie scores, validating the hypothesis that college scoring prowess translates to professional success to some extent. Effective Field Goal Percentage (eFG%) and True Shooting Percentage (TS%): These variables did not show significant predictive power in the model, suggesting that shooting efficiency in college may not directly correlate with NBA success, possibly due to differences in game pace, defensive intensity, and other professional factors.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="summary-of-findings" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-findings">Summary of Findings</h3>
<p>Our study aimed to predict NBA rookie success from college basketball statistics, focusing on points per game as a key indicator of performance. The analysis utilized linear regression and multilayer perceptron (MLP) models to determine the predictive power of college points per game, effective field goal percentage (eFG%), and true shooting percentage (TS%). The results highlighted that while college points had a statistically significant positive impact on NBA rookie points, the shooting percentages did not show strong predictive power. This suggests that while scoring ability in college can be a predictor of scoring in the NBA, factors measured by eFG% and TS% in college settings do not translate directly to professional success.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">Limitations</h3>
<p>One major limitation of our study is the potential for overfitting, especially with the MLP model, which could compromise the generalizability of our findings. The models demonstrated low R² values, indicating they captured only a small fraction of the variance in rookie NBA points. This could be due to the complexity of NBA success, which is influenced by a myriad of factors beyond collegiate statistical performance such as physical attributes, psychological factors, and team dynamics.</p>
<p>The dataset’s scope could also limit the analysis. For instance, the dataset includes only players who made it to the NBA, potentially omitting college players who did not progress to professional basketball. This selection bias might distort the relationship between college statistics and NBA success.</p>
</section>
<section id="reliability-and-validity" class="level3">
<h3 class="anchored" data-anchor-id="reliability-and-validity">Reliability and Validity</h3>
<p>While the data sources are reliable, being derived from comprehensive sports statistics databases, the validity of the conclusions might still be affected by the aforementioned selection bias and the exclusion of variables such as player injuries, mid-season trades, and changes in team strategy. These factors are crucial for a holistic assessment of a player’s performance but were not available in the datasets used.</p>
</section>
<section id="future-work" class="level3">
<h3 class="anchored" data-anchor-id="future-work">Future Work</h3>
<p>To enhance the robustness of future models, it would be beneficial to incorporate additional predictors such as player age at draft, physical measurements (e.g., height, wingspan), and perhaps more nuanced metrics of player efficiency and defensive contributions. Including data on player development over their first few NBA seasons could also help in understanding how college performance correlates with long-term professional success.</p>
<p>Advanced modeling techniques could also be explored. For instance, ensemble methods like random forests or boosted trees might capture complex nonlinear relationships more effectively than MLPs or linear models. Furthermore, incorporating player tracking data, which includes detailed movement data during games, could provide deeper insights into how college performance translates into NBA contexts.</p>
<p>Future studies should also consider integrating qualitative assessments such as scouting reports to complement the quantitative analysis. Comparisons with existing literature on predictors of sports performance would help in contextualizing the findings within broader sports analytics research.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>